package burlap.oomdp.stateserialization;

import burlap.oomdp.core.states.State;

/**
 * A factory interface for generating {@link burlap.oomdp.stateserialization.SerializableState} instances from an input
 * {@link burlap.oomdp.core.states.State} by using the {@link #serialize(burlap.oomdp.core.states.State)} method. This
 * interface requires a {@link #getGeneratedClass()} method that reports the specific {@link burlap.oomdp.stateserialization.SerializableState}
 * implementation that is returned so that complex classes that have {@link burlap.oomdp.core.states.State} instances
 * to be turned into a {@link burlap.oomdp.stateserialization.SerializableState} can map them to the appropriate class type.
 * @author James MacGlashan.
 */
public interface SerializableStateFactory {

	/**
	 * Takes a {@link burlap.oomdp.core.states.State} and turns it into a {@link burlap.oomdp.stateserialization.SerializableState}.
	 * @param s the input {@link burlap.oomdp.core.states.State} to convert.
	 * @return a {@link burlap.oomdp.stateserialization.SerializableState}
	 */
	SerializableState serialize(State s);

	/**
	 * Returns the {@link burlap.oomdp.stateserialization.SerializableState} implementation that is generated by this factory.
	 * @return the {@link java.lang.Class} of the {@link burlap.oomdp.stateserialization.SerializableState} implementation that is generated by this factory.
	 */
	Class<?> getGeneratedClass();
}
